title: A starting point
email: #
description: >-
  My first self-built website and testing ground.
baseurl: "/basic-site"
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: #
github_username:  rabbitxyt

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed 
defaults:
  -
    scope:
      path: "image-gallery"
    values:
      permalink: /:path/:basename:output_ext


port: 4001