title: A starting point
email: rabbitxyt@gmail.com
description: >-
  This is my first self-built site using Github Pages and Jekyll. Check out the post if you are interested in building one yourself.
baseurl: "/basic-site"
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: yiting_xiao
github_username:  rabbitxyt

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed